apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-deployment
  labels:
    app: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
       app: nginx-server
  template:
    metadata:
      labels:
         app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: nginx:1.19.4
        ports:
         - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "20m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: ClusterIP
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - as.rodriguez.student.lasalle.com
    secretName: nginx-certs-keys
  rules:
   - host: as.rodriguez.student.lasalle.com
     http: 
      paths:
        - path: "/"
          pathType: Prefix
          backend:
           service:
            name: service-nginx
            port:
              number: 80
